language: node_js
node_js:
  - "8.12.0"
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: s3
  access_key_id:
    secure: GoOx1y1TX58i0ggHIUUwGvAHmUJc5VvTqtEB+YTsF6DhM6+jb66JlHgfBW9bul0HrgORfKjbXGKdloohQTuhFR1VHFQY0HKyZn9UONeQtHHnRtu3YRzZo3aswh+zr7xtyr2AEniJYOE51mBQqblxdvP60qWJIxcL9rE/Ebvemq3JSl/UBj+lg6ZfGRTWV5UqhH9A89ElkqhCIsWEfSbeW/fM8zg35hDDfabKlHbUzYBUZUPzZJ7zXa59NdCbpI7/5wnPXveL3hYGZZkc6IcbRMyGoYL2PuBER19uoCVaQMXytc7qQ31bSw9oelrAahlTNXQJ+FOKJGCMCnW2MT8xRqaJjNftgUBZww3Y046NcHqX3o/YdCgpK0ttex6sG9ydWpRG4twxP+uxqr+vyn2CL+WiX23uPwErCRI0WooLa01E93o9MusPx7+y5M9+E3a+Hz8xcICRq5KdGqchwj0Z8oE9OttaubbRo9COwwoBqO+VwiY9RePPmHFeHcA8Tov6x3v2dCdqZZFO4tFc1evyGUWkMZPpnN1wMtgrwTkgY+iULXMFcLvxefq2Z8ZrDT+h7+mDmInG3IYQaVJT1hsVYye3aYMMi9pYAfn1mZ2MLNAMw266iEtMUcc8occKVpbfDJgLBq/ZDRlZxaQh7vNaM+XsfF3xeb1/2ETGTdgKbX8=
  secret_access_key:
    secure: 0xKfqBRcx9lEayLCroeHwQv7iYoEFkBIT6IWublXu0aUK56SfXN4zX0+6sn5C01eewrMBmN8qABZFlwaLaPcz9uum0E97ha+ramYAg5PF5RZ3fNQR5jVpdJ6CgNz2wtoj2QNIxeDUnDcUS4iIY4dcyAn/Wf9ydnJ/i+MipSvCHH6AcUsjxAsOmmNPjAi0AUENEOl58c6G272H3/KdUTEgG29+YUdllc8/dJBfRKUPsth4qX9NBDvJPUksQPda0pZ8bVQkcJ4HuidCNxKfIznnRMNdMpxP8ESTQF4Jk0aQeV73Ta8JWLc7MPvZi+ytTpuYZFkuk8rRnRNnnp8ftc0mrQeClOP09DYGpDToF50dWdBQcV2qXOBd20DAf7q0jfhAzQfOu8vAnuxY1Cud3HJqBmL1LeYr9ebYIYOmxVpGWUZKx6vGNujeswvt4BsIIBflPBuQ6VwgU9I75zRRf1VjcAsRqNRdMOhVkmU5FS+hrGkHFQrq8kfWIWUmm6dajAJcvVZCRqoq2vHQwAxOr2xIr6HZSebWPrIXUWG9v/lDoQtPkKfhGBEQDxmJrz2IJNnZWdiF3fB2RgcF9EZ8TKdeR7lGfGcXUrqGOW0lCuj7rQ8xH8V7S/+fpiF/4pqLogPvyFquygm3jaCix2UPdG/P79MLDEciM7Qiw2xL916nEE=
  bucket: heidiandkeith.com
  region: us-west-2
  acl: public_read
  local_dir: build
  skip_cleanup: true
branches:
  only:
  - publish
